#!/usr/bin/env node
/**
 * Verify a First Read provenance signature. No dependencies, no First Read code, no network call
 * to First Read. Node 16+.
 *
 *   node verify-example.mjs binding.json document.txt [revocations.json]
 *
 * `binding.json` is a record exported from First Read. `document.txt` is the document text it
 * claims to describe. Exit code 0 means the signature holds and the text is unaltered.
 *
 * THE POINT OF THIS FILE: if you can run it, you never have to trust First Read — or ask them for
 * anything — to settle a question about a document's origin.
 */
import { createHash, createPublicKey, verify } from 'node:crypto';
import { readFileSync } from 'node:fs';

const [, , bindingPath, documentPath] = process.argv;
if (!bindingPath || !documentPath) {
  console.error('usage: node verify-example.mjs <binding.json> <document.txt> [revocations.json]');
  process.exit(2);
}

const raw = JSON.parse(readFileSync(bindingPath, 'utf8'));
const document = readFileSync(documentPath, 'utf8');
const manifest = JSON.parse(readFileSync(new URL('./manifest.json', import.meta.url), 'utf8'));

/*
  ── ACCEPT THE FILE FIRST READ ACTUALLY HANDS PEOPLE ──

  This file spells the fields docId/docType. The writer-facing export spells them
  documentId/documentType. Nobody noticed for two days because every test was written by someone
  who knew the schema and hand-built the input.

  The failure mode is the worst one available to this script: a missing key is `undefined`, which
  JSON.stringify turns into `null`, which produces a well-formed payload with the wrong bytes. So
  an outsider following the published instructions on a GENUINE record got

      signature valid    : NO

  — a false accusation of forgery against an honest writer, generated by our own verifier, with
  nothing on screen hinting that the input was misread. Found 2026-08-20 by running this file
  against a real export instead of a fixture.

  So: accept either spelling, and REFUSE TO GUESS when a required field is absent under both.
  Exiting loudly beats verifying a payload built out of nulls.
*/
const pick = (...names) => {
  for (const n of names) if (raw[n] !== undefined) return raw[n];
  return undefined;
};

const binding = {
  ...raw,
  version: pick('version'),
  docId: pick('docId', 'documentId'),
  docType: pick('docType', 'documentType'),
  showId: pick('showId'),
  ownerId: pick('ownerId'),
  contentFingerprint: pick('contentFingerprint'),
  // Genuinely nullable — a record can name no voice profile. Absent and null are different.
  profileFingerprint: pick('profileFingerprint') ?? null,
  savedAt: pick('savedAt'),
  signature: pick('signature'),
  chainIndex: pick('chainIndex') ?? null,
  chainElement: pick('chainElement') ?? null,
  identitySessionId: pick('identitySessionId') ?? null,
  // v4. Genuinely nullable — a document we generated nothing for carries neither.
  toolOutputFingerprint: pick('toolOutputFingerprint') ?? null,
  toolOutputMethod: pick('toolOutputMethod') ?? null,
};

const required = ['version', 'docId', 'showId', 'ownerId', 'contentFingerprint', 'docType',
  'savedAt', 'signature'];
const missing = required.filter((f) => binding[f] === undefined || binding[f] === null);
if (missing.length) {
  console.error(`This record is missing required field(s): ${missing.join(', ')}.`);
  console.error('Refusing to verify — a payload built with a missing field would report a genuine');
  console.error('record as invalid. Check you passed the record object itself, not the whole export');
  console.error('file: an export contains a "records" array and each element is one record.');
  process.exit(2);
}

if (binding.version >= 2 && (binding.chainIndex === null || binding.chainElement === null)) {
  console.error(`A v${binding.version} record must carry chainIndex and chainElement; this one does not.`);
  console.error('Refusing to verify rather than silently substituting nulls.');
  process.exit(2);
}

/** The published fingerprint rule. CRLF to LF, strip trailing spaces/tabs per line, trim, SHA-256. */
const fingerprint = (text) =>
  createHash('sha256')
    .update(text.replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, '').trim(), 'utf8')
    .digest('hex');

/*
  A version this file has never heard of must be reported as UNSUPPORTED, never verified in the
  newest shape it happens to know. Guessing produces "signature valid: NO" on a record that is
  perfectly sound — the same false-forgery outcome described above, arriving from the future
  instead of from the past. Update this constant in the same commit that adds a field.
*/
const NEWEST_KNOWN_VERSION = 4;
if (binding.version > NEWEST_KNOWN_VERSION) {
  console.error(`This record is version ${binding.version}; this file only knows up to v${NEWEST_KNOWN_VERSION}.`);
  console.error('UNSUPPORTED — not verified and NOT invalid. Fetch a newer copy of this script from');
  console.error('https://github.com/First-Read-by-StoryHack/provenance before concluding anything.');
  process.exit(2);
}

/* 1. Does the text match what was signed? */
const contentOk = fingerprint(document) === binding.contentFingerprint;

/* 2. Which key was signing when this was saved? Never assume the current one. */
const t = Date.parse(binding.savedAt);
const key = manifest.keys.find(
  (k) => Date.parse(k.validFrom) <= t && (k.validUntil === null || t < Date.parse(k.validUntil)),
);

/*
  3. Rebuild the exact signed bytes. Field order is fixed and published; do not reorder.

     The shape depends on the record's own version, and rebuilding an older record in a newer shape
     would make a genuine signature read as forged. Fields are only ever APPENDED, so every index
     an earlier version established stays put.
*/
const payload = JSON.stringify([
  binding.version, binding.docId, binding.showId, binding.ownerId,
  binding.contentFingerprint, binding.profileFingerprint, binding.docType,
  // ISO-8601 with Z. A '+00:00' rendering is the same instant but different BYTES, and a
  // signature covers bytes — it would not verify. Normalise before comparing.
  new Date(binding.savedAt).toISOString(),
  // v2 added the chain position. v1 records predate it.
  ...(binding.version >= 2 ? [binding.chainIndex ?? null, binding.chainElement ?? null] : []),
  // v3 added the identity session, so a KYC record can be matched against the revocation list.
  ...(binding.version >= 3 ? [binding.identitySessionId ?? null] : []),
  /*
     v4 added a hash of the text First Read generated for this document, and — separately — an
     identifier for WHICH DEFINITION of "generated" was used when that hash was taken.

     The method matters to you as a reader. The definition changed once already, eight days after
     it was first written, when testing it against a real screenplay showed it was counting the
     tool quoting the writer's own pages back at him. If you recompute an overlap figure with
     today's definition against a record signed under an older one, you will get a different
     number, and that difference is NOT evidence of tampering. Read the method identifier, then
     look up what it meant: storyhack.io publishes each version.

     Neither field is a claim about who wrote anything. See the record's own limits text.
  */
  ...(binding.version >= 4
    ? [binding.toolOutputFingerprint ?? null, binding.toolOutputMethod ?? null]
    : []),
]);

const sigOk = key
  ? verify(null, Buffer.from(payload, 'utf8'), createPublicKey(key.publicKey),
      Buffer.from(binding.signature, 'base64'))
  : false;

/*
  4. If the record claims a government-ID check, that claim can have been WITHDRAWN since — a
     stolen document, synthetic media, a legal erasure order. Revocation never touches the
     signature, so a perfectly valid signature tells you nothing about it.

     Deliberately NOT a network call. The whole point of this file is that it needs nothing from
     First Read, and a verifier that phoned home would hand them the ability to answer selectively.
     Pass a list you fetched yourself, from whichever mirror you trust.

     Records from v3 onward name the identity session inside the signed payload, so the session
     cannot be swapped for an unrevoked one without breaking the signature. v1 and v2 records
     carry no session and cannot be revocation-checked at all — for those this prints UNKNOWN
     rather than implying a check it did not perform.
*/
const revocationPath = process.argv[4];
const claimsKyc = /kyc/i.test(binding.identity?.level ?? binding.identity ?? '');
let revocationLine = 'not applicable — this record does not claim a government-ID check';

if (claimsKyc) {
  if (!revocationPath) {
    revocationLine =
      'UNKNOWN — this record claims KYC identity and no revocation list was supplied.\n'
      + '                     Fetch /api/provenance/revocations (or a mirror) and pass it as the '
      + 'third argument.';
  } else {
    const list = JSON.parse(readFileSync(revocationPath, 'utf8'));
    const listKey = manifest.keys.find((k) => {
      const at = Date.parse(list.issuedAt);
      return Date.parse(k.validFrom) <= at && (k.validUntil === null || at < Date.parse(k.validUntil));
    });
    /* Entries sort by session id before signing, so rebuild in that order or the bytes differ. */
    const listPayload = JSON.stringify([
      list.version, list.issuedAt, list.nextUpdateBy, list.serial,
      [...list.entries]
        .sort((a, b) => (a.providerSessionId < b.providerSessionId ? -1 : 1))
        .map((e) => [e.providerSessionId, e.reason, e.revokedAt]),
    ]);
    const listSigOk = listKey && verify(
      null, Buffer.from(listPayload, 'utf8'),
      createPublicKey(listKey.publicKey), Buffer.from(list.signature ?? '', 'base64'),
    );

    if (!listSigOk) {
      revocationLine = 'UNKNOWN — the supplied revocation list does not verify. Do not rely on it.';
    } else if (Date.parse(list.nextUpdateBy) <= Date.now()) {
      /*
        An expired list is not an empty one. Reporting "not revoked" here would make withholding
        the list free, which is the one attack a signature cannot cover.
      */
      revocationLine =
        `UNKNOWN — the list expired on ${list.nextUpdateBy}. An out-of-date list is NOT evidence\n`
        + '                     that nothing is revoked. Fetch a current copy.';
    } else if (!binding.identitySessionId) {
      revocationLine =
        `UNKNOWN — list verified and current, but this record (v${binding.version}) names no\n`
        + '                     identity session, so there is nothing to match. Records signed '
        + 'before v3\n                     cannot be revocation-checked.';
    } else {
      const hit = list.entries.find((e) => e.providerSessionId === binding.identitySessionId);
      revocationLine = hit
        ? `REVOKED on ${hit.revokedAt} (${hit.reason}). The signature is still valid and the\n`
          + '                     document fingerprint and timestamp are unaffected — what changed '
          + 'is that\n                     the identity check can no longer be relied upon. This '
          + 'does NOT imply\n                     the record is forged or the writer acted in bad '
          + 'faith.'
        : `no — checked against a list issued ${list.issuedAt} carrying `
          + `${list.entries.length} revocation(s)`;
    }
  }
}

console.log(`document unaltered : ${contentOk ? 'yes' : 'NO — the text differs from what was signed'}`);
console.log(`key found for date : ${key ? key.fingerprint : 'NO — no published key covers ' + binding.savedAt}`);
console.log(`signature valid    : ${sigOk ? 'yes' : 'NO'}`);
console.log(`voice profile hash : ${binding.profileFingerprint ?? '(none recorded)'}`);
console.log(`identity revoked?  : ${revocationLine}`);
console.log('');
/*
  The success line branches on whether a voice profile was actually recorded. The first version
  said "against the recorded voice profile" unconditionally and printed that on a record whose
  profileFingerprint was null -- claiming something the record did not contain, in the one file
  whose whole purpose is letting someone check a claim. Caught by running it on a real document.
*/
if (contentOk && sigOk) {
  console.log(binding.profileFingerprint
    ? 'VERIFIED. First Read produced this document against the recorded voice profile, at the stated time.'
    : 'VERIFIED. First Read produced this document at the stated time. No voice profile was recorded\n'
      + 'for it, so this says nothing about which voice it was written against.');
  console.log('This does NOT by itself prove who the person behind the account is.');
  /*
    The qualifier is the point. A record claiming a government-ID check is exactly the record
    someone will lean on hardest, and printing a bare VERIFIED next to an unchecked identity claim
    is how this script would end up asserting more than it tested.
  */
  if (claimsKyc && !revocationLine.startsWith('no — checked')) {
    console.log('');
    console.log('CAVEAT: this record claims a government-ID check that this run did not clear.');
    console.log('The signature above is sound and says nothing about whether the identity');
    console.log('verification behind it still stands. See the "identity revoked?" line and treat');
    console.log('the identity as unconfirmed until it reads "no".');
  }
} else {
  console.log('NOT VERIFIED. Do not rely on this record.');
}

process.exit(contentOk && sigOk ? 0 : 1);
